import { $Enums } from '@prisma/client'

export const mockData = [
  {
    id: '1',
    description: 'Compra de supermercado',
    amount: 150.75,
    year: 2024,
    month: 9,
    status: $Enums.TransactionStatus.OPEN,
    categoryId: 'cat1',
    clusterId: null,
    methodId: 'method1',
    category: {
      id: 'cat1',
      description: 'Alimentação',
      type: $Enums.CategoryType.EXPENSE,
      clusterId: null,
    },
  },
  {
    id: '2',
    description: 'Pagamento de conta de energia',
    amount: 220.3,
    year: 2024,
    month: 9,
    status: $Enums.TransactionStatus.CLOSE,
    categoryId: 'cat2',
    clusterId: null,
    methodId: 'method2',
    category: {
      id: 'cat2',
      description: 'Contas',
      type: $Enums.CategoryType.EXPENSE,
      clusterId: null,
    },
  },
  {
    id: '3',
    description: 'Salário',
    amount: 3500.0,
    year: 2024,
    month: 9,
    status: $Enums.TransactionStatus.OPEN,
    categoryId: 'cat3',
    clusterId: null,
    methodId: 'method3',
    category: {
      id: 'cat3',
      description: 'Renda',
      type: $Enums.CategoryType.EXPENSE,
      clusterId: null,
    },
  },
  {
    id: '4',
    description: 'Assinatura de streaming',
    amount: 49.99,
    year: 2024,
    month: 9,
    status: $Enums.TransactionStatus.OPEN,
    categoryId: 'cat4',
    clusterId: null,
    methodId: 'method4',
    category: {
      id: 'cat4',
      description: 'Entretenimento',
      type: $Enums.CategoryType.EXPENSE,
      clusterId: null,
    },
  },
]
